export const DESIRED_JOBS = [
  '백엔드 개발자',
  '프론트엔드 개발자',
  '풀스택 개발자',
  '모바일 개발자 (iOS/Android)',
  '데이터 엔지니어',
  'ML/AI 엔지니어',
  'DevOps / 인프라',
  '보안 엔지니어',
  'QA 엔지니어',
  '데이터 분석가',
  '데이터 사이언티스트',
  '서비스 기획자 / PM',
  'UX/UI 디자이너',
  '퍼포먼스 마케터',
  '콘텐츠 마케터',
  '영업',
  '사업 개발 (BD)',
  '전략기획',
  '재무 / 회계',
  'HR / 인사',
  '직접 입력',
];

export const TECH_STACK_PLACEHOLDERS: Record<string, string> = {
  '백엔드 개발자': 'Java, Spring, MySQL, Redis, Docker',
  '프론트엔드 개발자': 'React, TypeScript, Next.js, Tailwind CSS',
  '풀스택 개발자': 'React, Node.js, TypeScript, PostgreSQL',
  '모바일 개발자 (iOS/Android)': 'Swift, Kotlin, Flutter, React Native',
  '데이터 엔지니어': 'Python, Spark, Airflow, Kafka, BigQuery',
  'ML/AI 엔지니어': 'Python, PyTorch, TensorFlow, MLflow, Kubernetes',
  'DevOps / 인프라': 'AWS, Kubernetes, Terraform, CI/CD, Linux',
  '보안 엔지니어': 'SIEM, 침투 테스트, 네트워크 보안, Python',
  'QA 엔지니어': 'Selenium, Jest, JMeter, Postman, 테스트 자동화',
  '데이터 분석가': 'Python, SQL, Tableau, Excel, A/B 테스트',
  '데이터 사이언티스트': 'Python, R, scikit-learn, SQL, 통계 분석',
  '서비스 기획자 / PM': 'Figma, Jira, Confluence, SQL, 데이터 분석',
  'UX/UI 디자이너': 'Figma, Sketch, Adobe XD, Prototyping, 사용자 리서치',
  '퍼포먼스 마케터': 'Google Ads, Meta Ads, GA4, SQL, 데이터 분석',
  '콘텐츠 마케터': 'SNS 운영, 카피라이팅, Canva, SEO, 영상 편집',
  '영업': 'CRM, Salesforce, Excel, 협상, 제안서 작성',
  '사업 개발 (BD)': '파트너십, 계약 협상, 시장 분석, Excel, 발표',
  '전략기획': '데이터 분석, PowerPoint, Excel, 재무 모델링, 시장 조사',
  '재무 / 회계': 'ERP, Excel, 재무제표 분석, 세무, 원가 관리',
  'HR / 인사': 'ATS, 채용 프로세스, 노무, 교육 기획, Excel',
};

export const DESIRED_INDUSTRIES = [
  'IT',
  '핀테크',
  '이커머스 / 유통',
  '게임',
  '헬스케어 / 바이오',
  '미디어 / 엔터테인먼트',
  '교육 / 에듀테크',
  '금융 / 보험',
  '제조 / 하드웨어',
  '부동산 / 건설',
  '물류 / 배송',
  '모빌리티 / 자동차',
  '통신',
  'AI / 딥테크',
  '에너지 / 환경',
  '컨설팅',
  '공공기관',
  '직접 입력',
];
